routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/en');

Route::group(['prefix' => '{language}'], function () {
    Route::view('/', 'welcome')->name('welcome');

    Auth::routes();

    Route::namespace('Admin')
        ->prefix('admin')
        ->name('admin.')
        ->middleware(['auth', 'permissions:access-admin-page'])
        ->group(function () {
            Route::resource('dashboard', 'DashboardController');

            Route::middleware('permissions:access-auth-panel')
                ->group(function () {
                    Route::get('users/generate-pwd-link/{id}', 'UserController@generateLink')->name('users.generate_pwd_link');
                    Route::get('users/search', 'UserController@search')->name('users.search');
                    Route::resource('users', 'UserController');

                    Route::resource('roles', 'RoleController');

                    Route::resource('permissions', 'PermissionController');
                });

            Route::resource('requests', 'RequestController');

            Route::redirect('/', route('admin.dashboard.index', app()->getLocale()))->name("default");
        });

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/demands/taken', 'DemandController@taken')->name('demands.taken');

    Route::resource('demands', 'DemandController')
        ->middleware('auth');

    Route::namespace('Admin')
        ->middleware('auth')
        ->group(function () {
            Route::view('/change-password', 'auth.change_password')->name('change_password.edit');
            Route::patch('/change-password', 'UserController@updatePassword')->name('change_password.update');
        });
});

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header row text-center justify-content-around">
                    @permission('access-demands-page')
                        <div class="col-12 col-md-4">
                            <a class="btn btn-primary" href="{{ route('demands.index') }}">{{ __('All Demands') }}</a>
                        </div>
                    @endpermission

                    @group('volunteer')
                        <div class="col-12 col-md-4 mt-2 mt-md-0">
                            <a class="btn btn-primary" href="{{ route('demands.taken') }}">{{ __('Taken Demands') }}</a>
                        </div>
                    @endgroup

                    @permission('make-demands')
                        <div class="col-12 col-md-4 mt-2 mt-md-0">
                            <a class="btn btn-primary" href="{{ route('demands.create') }}">{{ __('Make new Demand') }}</a>
                        </div>
                    @endpermission
                </div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ session()->pull('status') }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    @endif

                        <div class="container">
                            Count: {{ $demands->count() }}
                            <div id="demands">
                                @foreach($demands as $demand)
                                    <div class="card mx-auto mb-3">
                                        <div class="card-header d-inline-flex justify-content-between">
                                            {{ $demand->user()->first()->name }}
                                            @if(!$demand->finished && !$demand->taken)
                                                <form action="{{ route('demands.destroy', $demand->id) }}" method="post" onsubmit="return confirm('Do you really want to delete this Demand?');">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button class="btn btn-danger" type="submit"><i class="fas fa-trash"></i></button>
                                                </form>
                                            @endif
                                        </div>
                                        <div class="card-body">
                                            <h5 class="card-title">{{ $demand->title }}</h5>
                                            <p class="card-text">
                                                {{ $demand->description }}
                                            </p>
                                            <p>
                                                {{ __('State') }}: {{ $demand->finished ? __('Finished') : ($demand->taken ? __('In progress') : __('Not yet')) }}
                                            </p>
                                        </div>
                                        <div class="card-footer text-muted">
                                            {{ $demand->created_at->diffForHumans() }}
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection