routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/en');

Route::group(['prefix' => '{language}'], function () {
    Route::view('/', 'welcome')->name('welcome');

    Auth::routes();

    Route::namespace('Admin')
        ->prefix('admin')
        ->name('admin.')
        ->middleware(['auth', 'permissions:access-admin-page'])
        ->group(function () {
            Route::resource('dashboard', 'DashboardController');

            Route::middleware('permissions:access-auth-panel')
                ->group(function () {
                    Route::get('users/generate-pwd-link/{id}', 'UserController@generateLink')->name('users.generate_pwd_link');
                    Route::get('users/search', 'UserController@search')->name('users.search');
                    Route::resource('users', 'UserController');

                    Route::resource('roles', 'RoleController');

                    Route::resource('permissions', 'PermissionController');
                });

            Route::resource('requests', 'RequestController');

            Route::redirect('/', route('admin.dashboard.index', app()->getLocale()))->name("default");
        });

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/demands/taken', 'DemandController@taken')->name('demands.taken');

    Route::resource('demands', 'DemandController')
        ->middleware('auth');

    Route::namespace('Admin')
        ->middleware('auth')
        ->group(function () {
            Route::view('/change-password', 'auth.change_password')->name('change_password.edit');
            Route::patch('/change-password', 'UserController@updatePassword')->name('change_password.update');
        });
});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use \App\User;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Junges\ACL\Http\Models\Group;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

class RoleController extends Controller
{
    public function __construct()
    {
        $this->middleware('groups:superadmin')->except('index');
    }

    public function index()
    {
        $roles = auth()->user()->groups()->get();
        return view('admin.roles.index', compact('roles'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'slug' => ['required', 'string', 'max:255', 'unique:roles'],
            'description' => ['required', 'string'],
            'permissions' => ['array'],
        ]);

        $this->newGroup($request->name, $request->slug, $request->description);
        Group::where('slug', $request->slug)->first()->assignPermissions($request->permissions);

        return back()->withSuccess("Role '$request->name' has been successfully created.");
    }

    public function update(Request $request, $lang, $id)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'slug' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string'],
            'permissions' => ['array'],
        ]);

        $role = Group::findOrFail($id);
        $oldName = $role->name;
        $role->name = $request->name;
        $role->slug = $request->slug;
        $role->description = $request->description;
        $role->save();

        auth()->user()->getAllPermissions()->each(function ($item, $key) use ($role)
        {
            $role->revokePermissions($item);
        });

        if (isset($request->permissions)) {
            $role->assignPermissions($request->permissions);
        }
        return back()->withSuccess("Role '$oldName' has been successfully edited.");
    }

    public function destroy($lang, $id)
    {
        Group::destroy($id);
        return back()->withSuccess("Role has been successfully deleted.");
    }

    private function newGroup($name, $slug, $description)
    {
        try {
            $groupModel = app(config('acl.models.group'));
            try {
                $group = $groupModel->where('slug', $slug)
                    ->orWhere('name', $name)
                    ->first();
                if (! is_null($group)) {
                    return;
                }
                $groupModel->create([
                    'name'        => $name,
                    'slug'        => $slug,
                    'description' => $description,
                ]);
                return;
            } catch (\Exception $exception) {
                return;
            }
        } catch (\Exception $exception) {
            return;
        }
    }
}

resources/views/admin/roles/index.blade.php
@extends('layouts.admin')

@php
    use App\Permission;
@endphp

@section('header-links')
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#CreateRoleModal">
        Create Role
    </button>
    @component('components.Admin.RoleModal')
        @slot('mode')
            Create
        @endslot

        @slot('method')
            POST
        @endslot

        @slot('route')
            {{ route('admin.roles.store') }}
        @endslot
    @endcomponent
@endsection

@section('panel')
    <div class="">

        @include('components.error-success')

        @component('components.Admin.RoleModal')
            @slot('mode')
                Edit
            @endslot

            @slot('method')
                PATCH
            @endslot

            @slot('route')
                {{ route('admin.roles.update', '') }}
            @endslot
        @endcomponent
        <div class="table-responsive">
            <table class="table">
                <thead class="thead-dark">
                <tr class="">
                    <th scope="col" style="width: 5%">#</th>
                    <th scope="col" style="width: 15%">Name</th>
                    <th scope="col" style="width: 20%">Slug</th>
                    <th scope="col" style="width: 25%">Description</th>
                    <th scope="col" style="width: 25%">Permissions</th>
                    <th scope="col" style="width: 10%">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($roles as $role)
                    <tr>
                        <th scope="row">{{ $role->id }}</th>
                        <td>{{ $role->name }}</td>
                        <td>{{ $role->slug }}</td>
                        <td>{{ $role->description }}</td>
                        <td>
                            <ul>
                                @foreach($role->permissions()->get() as $permission)
                                    <li>{{ $permission->name }}</li>
                                @endforeach
                            </ul>
                        </td>
                        <td class="w-100" style="display: inline-flex">
                            @if(auth()->user()->hasGroup('superadmin'))
                                <button type="button"
                                        class="btn btn-primary mr-2"
                                        data-toggle="modal"
                                        data-target="#EditRoleModal"
                                        data-role_id="{{ $role->id }}"
                                        data-role_name="{{ $role->name }}"
                                        data-role_slug="{{ $role->slug }}"
                                        data-role_description="{{ $role->description }}"
                                        data-role_permissions="@foreach($role->permissions()->get() as $permission){{ $permission->slug."," }}@endforeach">
                                    <i class="fas fa-edit"></i>
                                </button>
                                @component('components.Admin.deleteBtn')
                                    @slot('title')
                                        Role
                                    @endslot

                                    @slot('route')
                                        {{ route('admin.roles.destroy', $role->id)}}
                                    @endslot

                                    @slot('icon')
                                        <i class="fas fa-minus-square"></i>
                                    @endslot
                                @endcomponent
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection