routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/en');

Route::group(['prefix' => '{language}'], function () {
    Route::view('/', 'welcome')->name('welcome');

    Auth::routes();

    Route::namespace('Admin')
        ->prefix('admin')
        ->name('admin.')
        ->middleware(['auth', 'permissions:access-admin-page'])
        ->group(function () {
            Route::resource('dashboard', 'DashboardController');

            Route::middleware('permissions:access-auth-panel')
                ->group(function () {
                    Route::get('users/generate-pwd-link/{id}', 'UserController@generateLink')->name('users.generate_pwd_link');
                    Route::get('users/search', 'UserController@search')->name('users.search');
                    Route::resource('users', 'UserController');

                    Route::resource('roles', 'RoleController');

                    Route::resource('permissions', 'PermissionController');
                });

            Route::resource('requests', 'RequestController');

            Route::redirect('/', route('admin.dashboard.index', app()->getLocale()))->name("default");
        });

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/demands/taken', 'DemandController@taken')->name('demands.taken');

    Route::resource('demands', 'DemandController')
        ->middleware('auth');

    Route::namespace('Admin')
        ->middleware('auth')
        ->group(function () {
            Route::view('/change-password', 'auth.change_password')->name('change_password.edit');
            Route::patch('/change-password', 'UserController@updatePassword')->name('change_password.update');
        });
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

use Junges\ACL\Traits\UsersTrait;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    use UsersTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'address', 'phone', 'country',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function demands()
    {
        return $this->hasMany(Demand::class);
    }

    public function request()
    {
        return $this->hasOne(Request::class);
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Permission;
use App\Role;
use App\User;
use Grosv\LaravelPasswordlessLogin\PasswordlessLogin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('permissions:access-auth-panel')->except('index', 'search');
        $this->middleware('permissions:edit-users-panel')->only('update', 'destroy', 'generateLink');
    }

    public function index()
    {
        $users = User::paginate(10);
        return view('admin.users.index', compact('users'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8'],
            'roles' => ['array'],
            'permissions' => ['array'],
        ]);

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);

        if (isset($request->permissions)) {
            $user->assignPermissions($request->permissions);
        }

        if (isset($request->roles)) {
            $user->assignGroup($request->roles);
        }

        return back()->withSuccess("User '$user->name' has been successfully created.");
    }

    public function update(Request $request, $lang, $id)
    {
        $user = User::findOrFail($id);
        User::findOrFail($request->id);
        $oldName = $user->name;
        $user->name = $request->name;
        $user->email = $request->email;
        if ($request->password) {
            $user->password = Hash::make($request->password);
        }
        $user->save();

        auth()->user()->groups()->get()->each(function ($item, $key) use ($user)
        {
            $user->revokeGroup($item);
        });
        auth()->user()->getAllPermissions()->each(function ($item, $key) use ($user)
        {
            $user->revokePermissions($item);
        });

        if (isset($request->roles)) {
            $user->assignGroup($request->roles);
        }

        if (isset($request->permissions)) {
            $user->assignPermissions($request->permissions);
        }

        return back()->withSuccess("User '$oldName' has been successfully edited.");
    }

    public function search(Request $request) {
        $query = $request->get('query');
        $category = $request->get('category');

        if (in_array($category, array("admin", "volunteer"))) {
            $users = User::group($category);
            if (isset($query) && $query != "") {
                $users = $users->where($category, 'like', '%'.$query.'%');
                dd("test");
            }
            $users =  $users->paginate(10);
        } elseif (in_array($category, array("name", "email", "id"))) {
            $users = User::where($category, 'like', '%'.$query.'%')->paginate(10);
        }

        return view('admin.users.index', compact('users'));
    }

    public function generateLink(Request $request)
    {
        $user = User::findOrFail($request->id);
        if ($user->hasGroup('superadmin')) {
            return abort(403, 'This is user is superadmin, you are not allowed to do this action');
        }
        return PasswordlessLogin::forUser($user)->generate().'<br>This link lasts only for 10 minutes';
    }

    public function updatePassword(Request $request)
    {
        $data = $request->validate([
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        $user = User::findOrFail(auth()->user()->id);
        $user->password = Hash::make($data['password']);
        $user->save();
        return redirect()->route('home');
    }

    public function destroy($lang, $id)
    {
        if (User::findOrFail($id)->hasGroup('superadmin')) {
            return abort(403, 'This is user is superadmin, you are not allowed to do this action');
        }
        User::destroy($id);
        return back()->withSuccess("User has been successfully deleted.");
    }
}

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('header-links')

    <div class="row w-100 text-center mt-3 mt-lg-0 ml-lg-2 mx-auto px-0">
        <form action="{{ route('admin.users.search') }}" class="col-sm-12 col-md-9 container-fluid border row w-100 mx-auto py-2">
            <div class="col-sm-12 col-md-1 my-auto">
                <a href="{{ route('admin.users.index') }}"><i class="fas fa-backward fa-2x mt-2"></i></a>
            </div>

            <div class="col-sm-12 col-md-5 my-auto">
                <input type="search" name="query" class="form-control" value="{{ request('query') }}">
            </div>

            <div class="col-sm-12 col-md-4 my-3 my-md-0">
                <select class="custom-select" name="category">
                    <option value="name" {{ request('category') == 'name' ? 'selected' : '' }}>name</option>
                    <option value="email" {{ request('category') == 'email' ? 'selected' : '' }}>email</option>
                    <option value="id" {{ request('category') == 'id' ? 'selected' : '' }}>id</option>
                    <option value="admin" {{ request('category') == 'admin' ? 'selected' : '' }}>admin</option>
                    <option value="volunteer" {{ request('category') == 'volunteer' ? 'selected' : '' }}>volunteer</option>
                </select>
            </div>

            <div class="col-sm-12 col-md-2 my-auto">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </form>

        <!-- Button trigger modal -->
        <div class="col-sm-12 col-md-3 d-flex justify-content-center my-2 my-md-0">
            <button type="button" class="btn btn-primary my-auto" style="width: initial" data-toggle="modal" data-target="#CreateUserModal">
                Create User
            </button>
        </div>
    </div>

    @component('components.Admin.UserModal')
        @slot('mode')
            Create
        @endslot

        @slot('method')
            POST
        @endslot

        @slot('route')
            {{ route('admin.users.store') }}
        @endslot
    @endcomponent
@endsection

@section('panel')
    <div class="">

        @include('components.error-success')

        @component('components.Admin.UserModal')
            @slot('mode')
                Edit
            @endslot

            @slot('method')
                PATCH
            @endslot

            @slot('route')
                {{ route('admin.users.update', '') }}
            @endslot
        @endcomponent

        <div class="table-responsive">
            <table class="table">
                <thead class="thead-dark">
                <tr class="">
                    <th scope="col" style="width: 10%">#</th>
                    <th scope="col" style="width: 20%">Name</th>
                    <th scope="col" style="width: 20%">Email</th>
                    <th scope="col" style="width: 30%">Roles</th>
                    <th scope="col" style="width: 20%">Actions</th>
                </tr>
                </thead>
                <tbody>

                @foreach($users as $user)
                    @if(! ($user->hasGroup('superadmin') || $user->id == auth()->user()->id))

                        <tr>
                            <th scope="row">{{ $user->id }}</th>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>
                                <ul>
                                    @foreach($user->groups()->get() as $role)
                                        <li>{{ $role->name }}</li>
                                    @endforeach
                                </ul>
                            </td>
                            <td class="w-100" style="display: inline-flex">
                                @permission('edit-users-panel')
                                    <button type="button"
                                            class="btn btn-primary mr-2"
                                            data-toggle="modal"
                                            data-target="#EditUserModal"
                                            data-user_id="{{ $user->id }}"
                                            data-user_name="{{ $user->name }}"
                                            data-user_email="{{ $user->email }}"
                                            data-user_roles="@foreach($user->groups()->get() as $role){{ $role->slug."," }}@endforeach"
                                            data-user_permissions="@foreach($user->getAllPermissions() as $permission){{ $permission->slug."," }}@endforeach">
                                        <i class="fas fa-edit"></i>
                                    </button>
                                    @component('components.Admin.deleteBtn')
                                        @slot('title')
                                            Role
                                        @endslot

                                        @slot('route')
                                            {{ route('admin.users.destroy', $user->id)}}
                                        @endslot

                                        @slot('icon')
                                            <i class="fas fa-user-minus"></i>
                                        @endslot
                                    @endcomponent

                                    @component('components.Admin.generateLinkBtn')
                                        @slot('id')
                                            {{ $user->id }}
                                        @endslot
                                    @endcomponent
                                @endpermission
                            </td>
                        </tr>
                    @endif
                @endforeach
                </tbody>
            </table>
            <div class="text-xs-center">
                {{ $users->links() }}
            </div>

        </div>
    </div>
@endsection