routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', '/en');

Route::group(['prefix' => '{language}'], function () {
    Route::view('/', 'welcome')->name('welcome');

    Auth::routes();

    Route::namespace('Admin')
        ->prefix('admin')
        ->name('admin.')
        ->middleware(['auth', 'permissions:access-admin-page'])
        ->group(function () {
            Route::resource('dashboard', 'DashboardController');

            Route::middleware('permissions:access-auth-panel')
                ->group(function () {
                    Route::get('users/generate-pwd-link/{id}', 'UserController@generateLink')->name('users.generate_pwd_link');
                    Route::get('users/search', 'UserController@search')->name('users.search');
                    Route::resource('users', 'UserController');

                    Route::resource('roles', 'RoleController');

                    Route::resource('permissions', 'PermissionController');
                });

            Route::resource('requests', 'RequestController');

            Route::redirect('/', route('admin.dashboard.index', app()->getLocale()))->name("default");
        });

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/demands/taken', 'DemandController@taken')->name('demands.taken');

    Route::resource('demands', 'DemandController')
        ->middleware('auth');

    Route::namespace('Admin')
        ->middleware('auth')
        ->group(function () {
            Route::view('/change-password', 'auth.change_password')->name('change_password.edit');
            Route::patch('/change-password', 'UserController@updatePassword')->name('change_password.update');
        });
});

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Junges\ACL\Http\Models\Permission;

class PermissionController extends Controller
{
    public function __construct()
    {
        $this->middleware('groups:superadmin')->except('index');
    }

    public function index()
    {
        $permissions = auth()->user()->getAllPermissions();
        return view('admin.permissions.index', compact('permissions'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'slug' => ['required', 'string', 'max:255', 'unique:permissions'],
            'description' => ['required', 'string'],
        ]);

        $this->newPermission($request->name, $request->slug, $request->description);

        return back()->withSuccess("Permission '$request->name' has been successfully created.");
    }

    public function update(Request $request, $lang, $id)
    {
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'slug' => ['required', 'string', 'max:255'],
            'description' => ['required', 'string'],
        ]);
        $permission = Permission::findOrFail($id);
        $oldName = $permission->name;
        $permission->name = $request->name;
        $permission->slug = $request->slug;
        $permission->description = $request->description;
        $permission->save();
        return back()->withSuccess("Permission '$oldName' has been successfully edited.");
    }

    public function destroy($lang, $id)
    {
        Permission::destroy($id);
        return back()->withSuccess("Permission has been successfully deleted.");
    }

    private function newPermission($name, $slug, $description)
    {
        try {
            $permissionModel = app(config('acl.models.permission'));

            try {
                $permission = $permissionModel->where('slug', $slug)
                    ->orWhere('name', $name)
                    ->first();
                if (! is_null($permission)) {
                    return;
                }
                $permissionModel->create([
                    'name'        => $name,
                    'slug'        => $slug,
                    'description' => $description,
                ]);
                return;
            } catch (\Exception $exception) {
                return;
            }
        } catch (\Exception $exception) {
            return;
        }
    }
}

resources/views/admin/permissions/index.blade.php
@extends('layouts.admin')

@section('header-links')

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#CreatePermissionModal">
        Create Permission
    </button>
    @component('components.Admin.PermissionModal')
        @slot('mode')
            Create
        @endslot

        @slot('method')
            POST
        @endslot

        @slot('route')
            {{ route('admin.permissions.store') }}
        @endslot
    @endcomponent
@endsection

@section('panel')
    <div class="">

        @include('components.error-success')

        @component('components.Admin.PermissionModal')
            @slot('mode')
                Edit
            @endslot

            @slot('method')
                PATCH
            @endslot

            @slot('route')
                {{ route('admin.permissions.update', '') }}
            @endslot
        @endcomponent

        <div class="table-responsive">
            <table class="table">
                <thead class="thead-dark">
                <tr class="">
                    <th scope="col" style="width: 5%">#</th>
                    <th scope="col" style="width: 15%">Name</th>
                    <th scope="col" style="width: 20%">Slug</th>
                    <th scope="col" style="width: 30%">Description</th>
                    <th scope="col" style="width: 20%">Roles</th>
                    <th scope="col" style="width: 10%">Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($permissions as $permission)
                    <tr>
                        <th scope="row">{{ $permission->id }}</th>
                        <td>{{ $permission->name }}</td>
                        <td>{{ $permission->slug }}</td>
                        <td>{{ $permission->description }}</td>
                        <td>
                            <ul>
                                @foreach($permission->groups()->get() as $role)
                                    <li>{{ $role->name }}</li>
                                @endforeach
                            </ul>
                        </td>
                        <td class="w-100" style="display: inline-flex">
                            @if(auth()->user()->hasGroup('superadmin'))
                                <button type="button"
                                        class="btn btn-primary mr-2"
                                        data-toggle="modal"
                                        data-target="#EditPermissionModal"
                                        data-permission_id="{{ $permission->id }}"
                                        data-permission_name="{{ $permission->name }}"
                                        data-permission_slug="{{ $permission->slug }}"
                                        data-permission_description="{{ $permission->description }}">
                                    <i class="fas fa-edit"></i>
                                </button>
                                @component('components.Admin.deleteBtn')
                                    @slot('title')
                                        Permission
                                    @endslot

                                    @slot('route')
                                        {{ route('admin.permissions.destroy', $permission->id)}}
                                    @endslot

                                    @slot('icon')
                                            <i class="fas fa-minus-square"></i>
                                    @endslot
                                @endcomponent
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection